import '../models/poster_models.dart';

class PosterSvgRenderer {
  const PosterSvgRenderer();

  String render(PosterExportData data) {
    final palette = _palette(data.coverAsset.themeKey);
    final metrics = data.metrics.take(5).toList();
    final metricBlocks = <String>[];
    for (var i = 0; i < metrics.length; i++) {
      final metric = metrics[i];
      final x = i.isEven ? 72 : 552;
      final y = 520 + (i ~/ 2) * 170;
      metricBlocks.add('''
<g transform="translate($x,$y)">
  <rect width="456" height="140" rx="26" fill="${palette.cardFill}" stroke="${palette.cardStroke}" stroke-width="2"/>
  <rect x="24" y="28" width="10" height="54" rx="5" fill="${_tone(metric.tone, palette)}"/>
  <text x="54" y="44" font-size="18" font-weight="600" fill="${palette.secondaryText}">${_escape(metric.label)}</text>
  <text x="54" y="88" font-size="34" font-weight="700" fill="${palette.text}">${_escape(metric.value)}</text>
  <text x="54" y="118" font-size="16" fill="${palette.secondaryText}">${_escape(metric.note)}</text>
</g>
''');
    }

    final keywords = data.keywords.take(3).toList();
    final keywordBlocks = <String>[];
    var keywordX = 72;
    const keywordY = 1128;
    for (final item in keywords) {
      final width = 74 + (item.length * 11);
      keywordBlocks.add('''
<g transform="translate($keywordX,$keywordY)">
  <rect width="$width" height="40" rx="20" fill="${palette.keywordFill}" stroke="${palette.cardStroke}" stroke-width="1.5"/>
  <text x="18" y="25" font-size="15" font-weight="600" fill="${palette.text}">#${_escape(item)}</text>
</g>
''');
      keywordX += width + 12;
    }

    final stateText =
        data.policy.showStateScore ? '${data.stateScore}' : data.stateLabel;

    return '''
<svg width="1080" height="1350" viewBox="0 0 1080 1350" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${palette.backgroundStart}"/>
      <stop offset="55%" stop-color="${palette.backgroundMid}"/>
      <stop offset="100%" stop-color="${palette.backgroundEnd}"/>
    </linearGradient>
    <linearGradient id="hero" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${palette.heroStart}"/>
      <stop offset="100%" stop-color="${palette.heroEnd}"/>
    </linearGradient>
    <clipPath id="coverClip">
      <rect x="612" y="46" width="280" height="340" rx="36"/>
    </clipPath>
  </defs>
  <rect width="1080" height="1350" fill="url(#bg)"/>
  <circle cx="170" cy="180" r="170" fill="${palette.glowA}" opacity="0.18"/>
  <circle cx="860" cy="220" r="210" fill="${palette.glowB}" opacity="0.12"/>
  <g transform="translate(72,56)">
    <rect x="0" y="0" width="44" height="44" rx="14" fill="${palette.badgeFill}" />
    <text x="58" y="20" font-size="24" font-weight="700" fill="${palette.text}">${_escape(data.brandLabel)}</text>
    <text x="58" y="44" font-size="16" font-weight="500" fill="${palette.secondaryText}">${_escape(data.periodLabel)} · ${_escape(data.dateLabel)}</text>
  </g>
  <g transform="translate(64,132)">
    <rect width="952" height="420" rx="42" fill="url(#hero)"/>
    ${_coverArt(data.coverAsset)}
    <text x="42" y="54" font-size="22" font-weight="700" fill="#FFFFFF">${_escape(data.title)}</text>
    <text x="42" y="270" font-size="${data.policy.showStateScore ? '148' : '72'}" font-weight="800" fill="#FFFFFF">${_escape(stateText)}</text>
    <text x="42" y="332" font-size="28" font-weight="600" fill="rgba(255,255,255,0.86)">${_escape(data.stateLabel)}</text>
  </g>
  ${metricBlocks.join('\n')}
  ${data.projectLabel == null ? '' : '<text x="72" y="1032" font-size="18" font-weight="600" fill="${palette.secondaryText}">Main Focus</text><text x="72" y="1072" font-size="34" font-weight="700" fill="${palette.text}">${_escape(data.projectLabel!)}</text>'}
  <text x="72" y="1188" font-size="26" font-weight="500" fill="${palette.text}">“${_escape(data.summary)}”</text>
  ${keywordBlocks.join('\n')}
  <text x="72" y="1288" font-size="14" font-weight="600" fill="${palette.secondaryText}">Generated by SkyOS</text>
  <text x="894" y="1288" font-size="14" font-weight="600" fill="${palette.secondaryText}">${_escape(data.policy.mode.label)}</text>
</svg>
''';
  }

  String _escape(String value) {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  String _tone(String tone, _SvgPalette palette) {
    switch (tone) {
      case 'primary':
        return palette.primary;
      case 'secondary':
        return palette.support;
      case 'accent':
        return palette.accent;
      case 'positive':
        return '#31B36B';
      case 'warning':
        return '#FF9B3F';
      default:
        return palette.primary;
    }
  }

  String _coverArt(PosterCoverAsset asset) {
    final imagePath = asset.imagePath;
    if (imagePath != null && imagePath.trim().isNotEmpty) {
      final href = 'file://${_escape(imagePath)}';
      return '''
<image x="612" y="46" width="280" height="340" href="$href" preserveAspectRatio="xMidYMid slice" clip-path="url(#coverClip)"/>
<rect x="612" y="46" width="280" height="340" rx="36" fill="none" stroke="rgba(255,255,255,0.24)" stroke-width="2"/>''';
    }
    switch (asset.artKind) {
      case PosterArtKind.focusBeam:
        return '''
<g transform="translate(612,46)">
  <path d="M90 280 L180 26 L270 280 Z" fill="rgba(255,255,255,0.22)"/>
  <rect x="175" y="34" width="10" height="224" rx="5" fill="rgba(255,255,255,0.56)"/>
</g>''';
      case PosterArtKind.growthWave:
        return '''
<g transform="translate(602,56)">
  <path d="M0 214 C96 56, 218 48, 320 168" stroke="rgba(255,255,255,0.56)" stroke-width="20" fill="none" stroke-linecap="round"/>
  <path d="M24 286 C112 156, 214 148, 292 232" stroke="rgba(255,255,255,0.34)" stroke-width="16" fill="none" stroke-linecap="round"/>
</g>''';
      case PosterArtKind.amberSun:
        return '''
<g transform="translate(622,76)">
  <circle cx="158" cy="90" r="42" fill="rgba(255,255,255,0.22)"/>
  <path d="M18 278 C116 122, 204 122, 302 278" stroke="rgba(255,255,255,0.52)" stroke-width="18" fill="none" stroke-linecap="round"/>
</g>''';
      case PosterArtKind.glassRibbon:
        return '''
<g transform="translate(588,82)">
  <path d="M-6 186 C84 58, 194 82, 314 142 C364 168, 402 164, 448 136 L448 242 C398 272, 352 278, 302 252 C198 198, 92 188, -6 262 Z" fill="rgba(255,255,255,0.16)"/>
</g>''';
      case PosterArtKind.projectCard:
        return '''
<g transform="translate(622,70)">
  <rect x="28" y="36" width="240" height="236" rx="34" fill="rgba(255,255,255,0.18)"/>
  <path d="M70 124 H226 M70 178 H188" stroke="rgba(255,255,255,0.54)" stroke-width="18" stroke-linecap="round"/>
</g>''';
      case PosterArtKind.galleryFrame:
        return '''
<g transform="translate(622,70)">
  <rect x="22" y="30" width="252" height="246" rx="36" fill="rgba(255,255,255,0.16)"/>
  <path d="M54 226 L122 144 L166 190 L216 126 L250 226" stroke="rgba(255,255,255,0.52)" stroke-width="16" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
</g>''';
      case PosterArtKind.uploadedImage:
        return '''
<g transform="translate(622,70)">
  <rect x="44" y="46" width="208" height="208" rx="36" fill="rgba(255,255,255,0.18)"/>
  <path d="M148 96 V204 M94 150 H202" stroke="rgba(255,255,255,0.56)" stroke-width="18" stroke-linecap="round"/>
</g>''';
    }
  }

  _SvgPalette _palette(String key) {
    switch (key) {
      case 'focus_blue':
        return const _SvgPalette(
          backgroundStart: '#08111F',
          backgroundMid: '#17335F',
          backgroundEnd: '#2759B6',
          heroStart: '#5F89FF',
          heroEnd: '#1D49C6',
          text: '#FFFFFF',
          secondaryText: 'rgba(255,255,255,0.72)',
          cardFill: 'rgba(255,255,255,0.10)',
          cardStroke: 'rgba(255,255,255,0.14)',
          badgeFill: 'rgba(255,255,255,0.16)',
          keywordFill: 'rgba(255,255,255,0.10)',
          primary: '#9ED0FF',
          support: '#87E5D8',
          accent: '#FFFFFF',
          glowA: '#9ED0FF',
          glowB: '#87E5D8',
        );
      case 'growth_mint':
        return const _SvgPalette(
          backgroundStart: '#0F1E1E',
          backgroundMid: '#1F5554',
          backgroundEnd: '#62A99E',
          heroStart: '#8AE8D8',
          heroEnd: '#208A78',
          text: '#FFFFFF',
          secondaryText: 'rgba(255,255,255,0.72)',
          cardFill: 'rgba(255,255,255,0.10)',
          cardStroke: 'rgba(255,255,255,0.14)',
          badgeFill: 'rgba(255,255,255,0.16)',
          keywordFill: 'rgba(255,255,255,0.10)',
          primary: '#D6FFF7',
          support: '#FFD599',
          accent: '#FFFFFF',
          glowA: '#8AE8D8',
          glowB: '#FFD599',
        );
      case 'amber_reset':
        return const _SvgPalette(
          backgroundStart: '#22160A',
          backgroundMid: '#6B4314',
          backgroundEnd: '#B9691A',
          heroStart: '#F7C36A',
          heroEnd: '#D87D19',
          text: '#FFFFFF',
          secondaryText: 'rgba(255,255,255,0.74)',
          cardFill: 'rgba(255,255,255,0.10)',
          cardStroke: 'rgba(255,255,255,0.16)',
          badgeFill: 'rgba(255,255,255,0.16)',
          keywordFill: 'rgba(255,255,255,0.10)',
          primary: '#FFF0CC',
          support: '#FFD2A1',
          accent: '#FFFFFF',
          glowA: '#F7C36A',
          glowB: '#FFD2A1',
        );
      default:
        return const _SvgPalette(
          backgroundStart: '#F1F5F9',
          backgroundMid: '#DCE6F2',
          backgroundEnd: '#C3D0E2',
          heroStart: '#DAE4F5',
          heroEnd: '#8EA8D7',
          text: '#111827',
          secondaryText: '#6B7280',
          cardFill: 'rgba(255,255,255,0.74)',
          cardStroke: '#E5E7EB',
          badgeFill: '#111827',
          keywordFill: 'rgba(255,255,255,0.74)',
          primary: '#2F6BFF',
          support: '#39C2BD',
          accent: '#8EA8D7',
          glowA: '#B9C8E8',
          glowB: '#DCE6F2',
        );
    }
  }
}

class _SvgPalette {
  const _SvgPalette({
    required this.backgroundStart,
    required this.backgroundMid,
    required this.backgroundEnd,
    required this.heroStart,
    required this.heroEnd,
    required this.text,
    required this.secondaryText,
    required this.cardFill,
    required this.cardStroke,
    required this.badgeFill,
    required this.keywordFill,
    required this.primary,
    required this.support,
    required this.accent,
    required this.glowA,
    required this.glowB,
  });

  final String backgroundStart;
  final String backgroundMid;
  final String backgroundEnd;
  final String heroStart;
  final String heroEnd;
  final String text;
  final String secondaryText;
  final String cardFill;
  final String cardStroke;
  final String badgeFill;
  final String keywordFill;
  final String primary;
  final String support;
  final String accent;
  final String glowA;
  final String glowB;
}
